---
- hosts: localhost
  remote_user: root
  become: yes
  become_method: sudo

  tasks:
       - include: /etc/ansible/tomcatInstall/tasks/InstallTomcat.yml
       - include: /etc/ansible/tomcatInstall/tasks/deployment.yml  
